---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goerli-erigon-data
  namespace: erigon
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
