---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goerli-erigon-rpcdaemon
  namespace: erigon
spec:
  selector:
    matchLabels:
      app: goerli-erigon-rpcdaemon
  revisionHistoryLimit: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: goerli-erigon-rpcdaemon
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - goerli-erigon-rpcdaemon
              topologyKey: "kubernetes.io/hostname"
      shareProcessNamespace: true
      containers:
        - name: goerli-erigon-rpcdaemon
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
          resources:
            requests:
              memory: 250Mi
              cpu: 100m
            limits:
              memory: 250Mi
              cpu: 100m
          image: thorax/erigon:v2022.01.01
          command: [
            "rpcdaemon",
            "--private.api.addr=goerli-erigon:9090",
            "--txpool.api.addr=goerli-erigon:9090",
            "--http.addr=0.0.0.0",
            "--http.vhosts=*",
            "--http.corsdomain=*",
            "--http.api=eth,debug,net",
            "--ws"
          ]
          ports:
            - containerPort: 8545
      restartPolicy: Always
